name: Update Status History
description: Update Status History
inputs:
  owner:
    description: Either the org name or the user name
    required: true
  project_name:
    description: The name of the project
    required: true
runs:
  using: composite
  steps:
    - env:
        OWNER: ${{ inputs.owner }}
        PROJECT_NAME: ${{ inputs.project_name }}
      run: .github/scripts/update.sh "${OWNER}" "${PROJECT_NAME}"
      shell: bash
      working-directory: ${{ github.action_path }}
